CREATE TABLE [dbo].[Users] (
    [UserId]                UNIQUEIDENTIFIER NOT NULL,
    [usertype]              NVARCHAR (10)    NOT NULL,
    [Username]              NVARCHAR (50)    NOT NULL,
    [Password]              NVARCHAR (100)   NOT NULL,
    [Salutation]            NVARCHAR (10)    NULL,
    [FirstName]             NVARCHAR (40)    NULL,
    [LastName]              NVARCHAR (30)    NOT NULL,
    [Sex]                   NVARCHAR (6)     NULL,
    [SocialSecurityNnumber] NVARCHAR (100)   NULL,
    [BloodGroupId]          UNIQUEIDENTIFIER NULL,
    [AddressLine1]          NVARCHAR (150)   NULL,
    [AddressLine2]          NVARCHAR (150)   NULL,
    [CityId]                UNIQUEIDENTIFIER NULL,
    [EmailId]               NVARCHAR (50)    NULL,
    [MobileNumber]          NVARCHAR (15)    NULL,
    [HomePhoneNumber]       NVARCHAR (15)    NULL,
    [WorkPhoneNumber1]      NVARCHAR (15)    NULL,
    [WorkPhoneNumber2]      NVARCHAR (15)    NULL,
    [Status]                NVARCHAR (8)     NOT NULL,
    [CreatedBy]             UNIQUEIDENTIFIER NOT NULL,
    [CreatedDate]           DATETIME         CONSTRAINT [DF_Users_CreatedDate] DEFAULT (getdate()) NULL,
    [UpdatedBy]             UNIQUEIDENTIFIER NULL,
    [UpdatedDate]           DATETIME         CONSTRAINT [DF_Users_UpdatedDate] DEFAULT (getdate()) NULL,
    [IP]                    NVARCHAR (50)    NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([UserId] ASC),
    CONSTRAINT [FK_Users_City] FOREIGN KEY ([CityId]) REFERENCES [dbo].[City] ([CityId])
);

